apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-app
spec:
  containers: 
    - name: flask-app-container
      image: flaskapp
      imagePullPolicy: Never
      env:
        - name: USERNAME
          value: "Marry"

---

apiVersion: v1
kind: Service
metadata:
  name: app-srv
spec:
  selector:
    app: flask-app
  type: NodePort
  ports:
    - targetPort: 5000
      port: 5000
      nodePort: 31000
          